# Configuration Fly.io pour le service PDF Call Times
app = "call-times-pdf-renderer"
primary_region = "cdg" # Paris

[build]

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[vm.mounts]]
  source = "pdf_cache"
  destination = "/tmp/pdfs"

[processes]
  app = "npm start"
